const getters = {
    tag: state => state.tags.tag,
    website: state => state.common.website,
    userInfo: state => state.user.userInfo,
    kongClient: state => state.user.kongClient,
    systemProfile: state => state.user.systemProfile,
    isDevProfile: state => state.user.isDevProfile,
    isProdProfile: state => state.user.isProdProfile,
    theme: state => state.common.theme,
    themeName: state => state.common.themeName,
    isShade: state => state.common.isShade,
    isCollapse: state => state.common.isCollapse,
    keyCollapse: (state, getters) => getters.screen > 1 ? getters.isCollapse : false,
    screen: state => state.common.screen,
    isLock: state => state.common.isLock,
    isFullScren: state => state.common.isFullScren,
    lockPasswd: state => state.common.lockPasswd,
    tagList: state => state.tags.tagList,
    tagWel: state => state.tags.tagWel,
    token: state => state.user.token,
    roles: state => state.user.roles,
    developerId: state => state.user.developerId,
    permission: state => state.user.permission,
    menu: state => state.user.menu,
    menuAll: state => state.user.menuAll,
    logsList: state => state.logs.logsList,
    logsLen: state => state.logs.logsList.length || 0,
    logsFlag: (state, getters) => getters.logsLen === 0,
    serviceTreeData: state => state.gateway.serviceTreeData
}
export default getters
